server:
  port: 8096
  address: 127.0.0.1

spring:
  application:
    name: hsm-simulator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hsmdb}
    username: ${SPRING_DATASOURCE_USERNAME:hsm}
    password: ${HSM_DB_PASSWORD:hsm_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

smdp:
  hsm:
    pin: ${HSM_PIN:1234}
