ALTER TABLE profile ADD COLUMN profile_class VARCHAR(255) DEFAULT 'OPERATIONAL';
ALTER TABLE profile ADD COLUMN mcc_mnc VARCHAR(255) DEFAULT '00101';
ALTER TABLE profile ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE profile ADD COLUMN downloaded_at TIMESTAMP;
ALTER TABLE profile ADD COLUMN order_id VARCHAR(255);
