server:
  port: 8094

spring:
  application:
    name: authelia-ldap
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/autheliadb}
    username: ${SPRING_DATASOURCE_USERNAME:authelia}
    password: ${SPRING_DATASOURCE_PASSWORD:authelia_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    in.hutta.ldap: DEBUG

ldap:
  port: 10389
  base-dn: dc=hutta,dc=in
  admin-dn: cn=admin,dc=hutta,dc=in
  admin-password: ${LDAP_ADMIN_PASSWORD:admin_password}
