[masters]
rbpi-master ansible_host=192.168.1.100 ansible_user=rbpi

[workers]
rbpi-worker-01 ansible_host=192.168.1.110 ansible_user=rbpi
rbpi-worker-02 ansible_host=192.168.1.120 ansible_user=rbpi

[all:vars]
ansible_python_interpreter=/usr/bin/python3
k3s_token=SecretClusterToken123!
k3s_version=v1.30.2+k3s1
