name: Deploy LPA Simulator (Self-Hosted)

on:
  push:
    branches:
      - main
    paths:
      - 'lpa-simulator/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-java-template.yml
    with:
      module-name: lpa-simulator
      service-name: lpa-simulator
      jar-name: lpa-simulator-1.0.0.jar
      remote-dir: /home/rbpi/lpa-simulator
      description: "LPA Simulator Service"
